default_stages: [commit]
repos:
  - repo: https://github.com/miki725/importanize/
    rev: master
    hooks:
      - id: importanize
        stages:
          - commit
          - push
        args:
          - --verbose
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        stages:
          - commit
          - push
        args:
          - --max-line-length=120
          - --diff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        entry: mypy -p exchange
        pass_filenames: false
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8